services:
  backend:
    build: ./backend
    container_name: match-predictor-backend
    network_mode: host
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_USER=${SUPABASE_USER}
      - SUPABASE_PASSWORD=${SUPABASE_PASSWORD}
      - FOOTBALL_API_URL=${FOOTBALL_API_URL}
      - FOOTBALL_API_KEY=${FOOTBALL_API_KEY}

  frontend:
    build: ./frontend
    container_name: match-predictor-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
